### ISSUE TITLE
Rsync hangs in alpine based docker image on error conditions

### ISSUE THREAD

**Issue by smileprem** [GoogleCloudPlatform/gsutil#548] opened 2018-08-14 01:41 UTC
**Issue:** On certain error conditions, (eg. Bucket does not exist, access denied exception, files were renamed during rsync etc), the `gsutil rsync -m` fails with an exception, but hangs forever. The script which triggered the `gsutil rsync -m` command simply waits for a exit code forever. 

This is specific to alpine based docker image `google/cloud-sdk:alpine`. It works fine on Debian based docker image `google/cloud-sdk:latest`.

**Steps to reproduce:**

1. Login to cloud and make sure gsutil is installed.
2. Copy this script to your local folder, name it script.sh

```
#!/bin/bash

DELAY=10

while true; do

    start=`date +%s`
    echo "Staring rsync (multi-threaded)"

    # Options for gsutil rsync
    # C - If an error occurs, continue to attempt to copy the remaining files
    # e - Exclude symlinks
    # d - Delete extra files under dst_url not found under src_url
    # r - Causes directories, buckets, and bucket subdirectories to be synchronized recursively

    gsutil -m rsync -Cedr gs://bucket-data-does-not-exist .

    exitCode=$?
    if [ $exitCode -ne 0 ]; then
        echo "Rsync execution failed with exit code "$exitCode
    else
        end=`date +%s`
        echo "Synchronization completed in "$((end-start))" seconds"
    fi

    sleep $DELAY

done

echo "Something terrible happened, the while loop is broken with error code "$?

# Let's exit with -1 to let k8s to restart the pod.
exit -1

```
2. Copy this Dockerfile
```
FROM google/cloud-sdk:alpine

COPY script.sh /

ENTRYPOINT ["./script.sh"] 
```
3. Build the docker image
```
docker build . -t smileprem001/test-rsync-alpine-issue:alpine
```
4. Run the docker image
```
docker run smileprem001/test-rsync-alpine-issue:alpine
```

The script will wait forever for the response from gsutil rsync command.

5. Replace the image name from `google/cloud-sdk:alpine` to `google/cloud-sdk:latest`.

Now the script will run in a loop.

**Comment by bpcreech** [comment] 2018-09-17 23:02
Seeing the same, using the iron/go image (which is also alpine)

**Comment by bpcreech** [comment] 2018-09-17 23:14
if this helps where's what happens when you try to rsync to a bucket but have no credentials:

```
/tmp/foobar # python -m pdb /google-cloud-sdk/bin/bootstrapping/gsutil.py  -m rsync -R -d -a public-read generated gs://www.bpcreech.com
> /google-cloud-sdk/bin/bootstrapping/gsutil.py(6)<module>()
-> """A convenience wrapper for starting gsutil."""
(Pdb) r
Building synchronization state...
Caught non-retryable exception while listing gs://www.bpcreech.com/: ServiceException: 401 Anonymous caller does not have storage.objects.list access to www.bpcreech.com.
CommandException: Caught non-retryable exception - aborting rsync
^CCaught CTRL-C (signal 2) - exiting
--Return--
> /google-cloud-sdk/bin/bootstrapping/gsutil.py(110)<module>()->None
-> except Exception as e:  # pylint: disable=broad-except
(Pdb) w
  /usr/lib/python2.7/bdb.py(400)run()
-> exec cmd in globals, locals
  <string>(1)<module>()->None
> /google-cloud-sdk/bin/bootstrapping/gsutil.py(110)<module>()->None
-> except Exception as e:  # pylint: disable=broad-except
(Pdb) 
```

**Comment by houglum** [comment] 2018-09-17 23:17
Alpine Linux must not like something about how we're using Python's multiprocessing library -- I've seen similar hangs on Windows where children-of-children processes don't join and gsutil will just hang at the end of execution.  I was debugging this earlier (someone else reported this), and it hangs after we end up finally calling `sys.exit(1)`.  To get around this on Windows, we force the process limit to 1, even if users specify otherwise.  Explicitly specifying a process count of 1 makes this run to completion on Alpine Linux as well.  So, a workaround that still uses a decent amount of parallelization would be something like this, which sets process count to 1 and thread count to <some high value like 32>:

```
gsutil -m \
    -o 'GSUtil:parallel_process_count=1' \
    -o 'GSUtil:parallel_thread_count=32' \
    cp -r /this-dir-does-not-exist gs://MYBUCKET
```

For documentation's sake, some of our internal users have also found this bug (https://issuetracker.google.com/issues/115499325, although that issue is only visible to Google folks).

**Comment by smileprem** [comment] 2018-09-17 23:40
Hi @houglum - Thanks for the update. Is there a deadline for the fix?. Or, could we update the google documentation rsync - to mention about this issue with alpine based images?.

https://cloud.google.com/storage/docs/gsutil/commands/rsync

It took a while for us to pinpoint the issue with the alpine docker image.

**Comment by houglum** [comment] 2018-09-18 00:00
It's not with rsync, specifically.  I reproduced it with a `gsutil cp` command.  We don't have an ETA for a fix, as we're still looking into figuring out exactly what's hanging, and whether a fix is feasible or if we should just limit the process count to 1 and call it fine.

**Comment by mfschwartz** [comment] 2018-10-13 02:53
The fix for this problem will be included in gsutil release 4.35.

**Comment by jakewins** [comment] 2019-04-18 00:06
@mfschwartz the 4.35 changelog just says multi processing was disabled in alpine; as the docs highlight, it seems the GIL gets in the way of concurrent compression when using threads. 

Would it be possible to consider this an outstanding issue, rather than a fixed problem?

Currently wrangling performance problems with uploading large files on alpine images..

**Comment by mfschwartz** [comment] 2019-04-18 01:19
@jakewins I'm not sure it would make sense to treat this as an outstanding issue, because we've decided (for various reasons) that disabling multiprocessing in Alpine is the workaround we are accepting. Marking it as an outstanding issue might imply to some users that we plan to do additional work to address the performance problem for Alpine.

Of course if someone wants to contribute a solution to the problem that makes Alpine work with multiprocessing, that would be welcome.

**Closed by mfschwartz** 2019-04-18 01:19 UTC

**Comment by jakewins** [comment] 2019-04-18 18:25
@mfschwartz got it. I was poking a bit at it yesterday, but realized while working on that reducing the compression level seemed to make a major difference for me, so now I'm not at all confident that the GIL was an issue. 

I was meaning to open a ticket asking about the compression level, but went ahead and wrote up a PR to make it easier to show the difference and to propose one way to incorporate it: https://github.com/GoogleCloudPlatform/gsutil/pull/749
