### ISSUE TITLE
MacOS version was not pre-compiled with crcmod

### ISSUE THREAD

**Issue by clintron** [GoogleCloudPlatform/gsutil#1123] opened 2020-10-14 19:31 UTC
The gsutil manual for crc32c claims that:
>  gsutil distributes a pre-compiled version of crcmod for macOS, so you shouldn't
  need to compile and install it yourself. If for some reason the pre-compiled
  version is not being detected, please let the Google Cloud Storage team know
  (see ``gsutil help support``).

But my macOS build is showing `False` for `compiled crcmod`:
```
# gsutil version -l                                                                          
gsutil version: 4.52
checksum: 38b524a8455fe2a596d5d666b17b8795 (OK)
boto version: 2.49.0
python version: 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
OS: Darwin 19.6.0
multiprocessing available: True
using cloud sdk: True
pass cloud sdk credentials to gsutil: True
config path(s): /Users/cstevenson/.boto, /Users/cstevenson/.config/gcloud/legacy_credentials/cstevenson@snapchat.com/.boto
gsutil path: /Users/cstevenson/google-cloud-sdk/bin/gsutil
compiled crcmod: False
installed via package manager: False
editable install: False
```

**Comment by clintron** [comment] 2020-10-14 19:33
I manually compiled it as suggested, but I just wanted to let you guys know.

**Comment by clintron** [comment] 2020-10-19 18:50
As mentioned in another issue, this can be resolved by installing Python 3.7 (or earlier) and pointing your Google Cloud SDK at it.  For example:
```
# In ~/.zshrc (or whatever your shell uses)
export CLOUDSDK_GSUTIL_PYTHON="/usr/local/opt/python@3.7/bin/python3"
```

**Comment by directionless** [comment] 2020-11-13 04:15
Looks like a dup of #1073

**Comment by mihar** [comment] 2020-12-17 19:10
I have the same problem. Added env vars pointing to python3 as well, to no avail.

```
gsutil version: 4.57
checksum: 43b6eb5e813ffed48ec2e541025259cb (OK)
boto version: 2.49.0
python version: 3.9.1 (default, Dec 10 2020, 11:11:14) [Clang 12.0.0 (clang-1200.0.32.27)]
OS: Darwin 20.2.0
multiprocessing available: True
using cloud sdk: True
pass cloud sdk credentials to gsutil: True
config path(s): /Users/XXX/.config/gcloud/legacy_credentials/XXX/.boto
gsutil path: /Users/XXX/Code/google-cloud-sdk/bin/gsutil
compiled crcmod: False
installed via package manager: False
editable install: False
```

I've run `sudo pip3 install -U crcmod`.

**Comment by axeltidemann** [comment] 2021-02-03 08:53
Same here. It would be great to get a fix for this.

**Comment by dilipped** [comment] 2021-02-03 15:21
This might happen if pip3 is pointing to a different Python binary. One way to fix it would be to find out which python binary your gsutil command is using and try to run pip install on that binary.

If you are running gsutil installed with `gcloud`, then you can find the python path by running `gcloud info`. Check for `Python Location` in the result.
Then use that path to run the following command
```
<your python path> -m pip install -U crcmod
```

If you are setting `CLOUDSDK_GSUTIL_PYTHON`, then you can do
```
CLOUDSDK_GSUTIL_PYTHON -m pip install -U crcmod
```

Let me know if that works.

**Comment by axeltidemann** [comment] 2021-02-03 15:47
Thanks for your input - but it still does not work.
```
>/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install -U crcmod
Requirement already up-to-date: crcmod in /Library/Python/3.8/site-packages (1.7)
```
As shown here:
```
>gsutil version -l
gsutil version: 4.58
checksum: 44d45a3d8964178345c7623917d745ea (OK)
boto version: 2.49.0
python version: 3.8.2 (default, Oct  2 2020, 10:45:42) [Clang 12.0.0 (clang-1200.0.32.27)]
OS: Darwin 19.6.0
multiprocessing available: True
using cloud sdk: True
pass cloud sdk credentials to gsutil: True
config path(s): /Users/axel.tideman/.boto, /Users/axel.tideman/.config/gcloud/legacy_credentials/axel.tidemann@takealot.com/.boto
gsutil path: /Users/axel.tideman/Downloads/google-cloud-sdk/bin/gsutil
compiled crcmod: False
installed via package manager: False
editable install: False
```

**Comment by dilipped** [comment] 2021-02-03 15:54
Can you please try uninstalling and reinstalling it again?
```
/Library/Developer/CommandLineTools/usr/bin/python3 -m pip uninstall crcmod
/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install -U crcmod
```

**Comment by axeltidemann** [comment] 2021-02-03 16:00
Still same output of `gsutil version -l`, unfortunately. (Technical note: I had to `sudo` the two commands you posted.)

**Comment by dilipped** [comment] 2021-02-03 16:07
That probably means that it is not able compile the Python C extension. 

Did you follow the steps here https://cloud.google.com/storage/docs/gsutil/addlhelp/CRC32CandInstallingcrcmod#macos
i.e did you install XCode before running the installation?

**Comment by dilipped** [comment] 2021-02-03 16:55
My guess would be that you will need it so that the Python C extension for `crcmod` can be compiled to binary module.
you can do `xcode-select --install`

**Comment by axeltidemann** [comment] 2021-02-03 20:34
Unfortunately, that does not solve it either - this is the result from the command.
```
>xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by dilipped** [comment] 2021-02-03 20:58
One last thing. Do you have `gcc` or `make` available on your machine. You can type those command to see if those are available. Basically you need a compiler to compile the Python C extension for crcmod.

**Comment by axeltidemann** [comment] 2021-02-04 05:32
Yes, they are both included the command line tools.
```
>gcc
clang: error: no input files
```
```
>make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by dilipped** [comment] 2021-02-04 21:21
That's strange. Given that you have gcc, the crcmod should have compiled the C extension when you did `pip install crcmod`. I am not able to reproduce this problem on my end, because for me, it always compiles the C extension. You can use the `--verbose` flag on pip to check if the crcmod is compiling the C extension.
`pip  install --verbose  crcmod`
If it says `Using cached wheel link ...` delete that file path and try uninstalling and re-installing again.
You should be able to see something like
```
building 'crcmod._crcfunext' extension
```



But anyway, I have rolled out a PR to update the .so file for Python3. https://github.com/gsutil-mirrors/crcmod-osx/pull/3
This should make compiled crcmod available directly without having to install crcmod via pip.

**Comment by dilipped** [comment] 2021-02-05 01:24
Please ignore gsutil-mirrors/crcmod-osx#3. It breaks because of some Python3 dependencies.

**Comment by axeltidemann** [comment] 2021-02-05 15:11
I tried installing with `--verbose`, but it was not using the cache, so that can't be it either.

**Comment by dilipped** [comment] 2021-02-05 15:18
And did you see this line
```
building 'crcmod._crcfunext' extension
```
in your verbose logs?

**Comment by axeltidemann** [comment] 2021-02-05 15:27
No.

**Comment by dilipped** [comment] 2021-02-05 16:20
OK. Thanks for the info. That means when you do a pip install, it is not able to compile the C extension and because of that gsutil is correctly indicating that Compiled crcmod is not found. 

This sounds like something specific to your machine/environment. You will probably have to figure out why pip install is not building the C extension on your machine. You can try manually building it as well by following the steps here https://pypi.org/project/crcmod/.

Does this issue persist with other Python versions as well? You can try pyenv https://github.com/pyenv/pyenv which let you easily switch between multiple Python versions.

BTW, which OSX  version are you using?

**Comment by axeltidemann** [comment] 2021-02-09 07:46
I got it to install the compiled version by creating a new virtual environment, and then doing a `pip install crcmod` in that one. Previously, I did not use a virtual environment, because I wanted the `crcmod` installation to be system wide, and not having to start the virtual environment just to issue `gsutil` commands. I suppose this can be down to subtleties in Python installation (I have a Homebrew Python 3.7 in addition to 2.7.16 and 3.8.2, for instance). 

Just a note: when doing the pip installation, it still did not say `building 'crcmod._crcfunext' extension`, I assume the distribution of a binary version with macOS works. This is what I did:

```
>python3.7 -m venv crcmod-fix

>source crcmod-fix/bin/activate

(crcmod-fix) >pip install crcmod
Processing ./Library/Caches/pip/wheels/dc/9a/e9/49e627353476cec8484343c4ab656f1e0d783ee77b9dde2d1f/crcmod-1.7-cp37-cp37m-macosx_10_15_x86_64.whl
Installing collected packages: crcmod
Successfully installed crcmod-1.7

(crcmod-fix) >gsutil version -l 
gsutil version: 4.58
checksum: 44d45a3d8964178345c7623917d745ea (OK)
boto version: 2.49.0
python version: 3.7.9 (default, Nov 20 2020, 18:45:38) [Clang 12.0.0 (clang-1200.0.32.27)]
OS: Darwin 19.6.0
multiprocessing available: True
using cloud sdk: True
pass cloud sdk credentials to gsutil: True
config path(s): /Users/XXX/.boto, /Users/XXX/.boto
gsutil path: /Users/XXX/Downloads/google-cloud-sdk/bin/gsutil
compiled crcmod: True
installed via package manager: False
editable install: False
```

So this is at least a workaround with just the minor nuisance to start the virtualenv. I am on 10.15.7.

**Comment by dilipped** [comment] 2021-02-09 15:47
Thanks for sharing. Glad that you were able to get it to work. FYI, to see the line `building 'crcmod._crcfunext' extension`, you will need to install it using the --verbose option: `pip install --verbose crcmod`.  

You can also try installing it directly on the python 3.7.9 version installed on your machine. I think earlier you were using 3.8?

**Comment by axeltidemann** [comment] 2021-02-10 06:14
Even with `pip install --verbose crcmod` I don't get the `building 'crcmod._crcfunext' extension` message. Furthermore, I tried installing it with the Python 3.7.9 version _outside_ a virtualenv (i.e. so it would be system-wide), but still not picked up - which kind of makes sense, since in `gsutil version -l` it does say `python version 3.8.2` (once again, not inside the virtualenv). 

So far, the only way to get it to work for me has been to install `crcmod` inside a virtualenv.

**Comment by dilipped** [comment] 2021-02-10 16:12
Gcloud will point to the default python binary on your machine. To point the Cloud SDK to use a specfic python binary, you can set the `CLOUDSDK_GSUTIL_PYTHON` env variable
e.g
```
export CLOUDSDK_GSUTIL_PYTHON=<path to your Python 3.7.9 binary>
```

**Comment by axeltidemann** [comment] 2021-02-11 09:24
Hey, that fixed it! Thanks! I suppose for some reason the `pip install crcmod` was not installing to the `3.8.2` system-wide packages even when specifying that Python version during the install, adding to the confusion.

@clintron I think you can close this issue now.

**Comment by dilipped** [comment] 2021-02-20 18:33
Closing this one. Feel free to reopen or file a new issue if this is still a problem. Thanks!

**Closed by dilipped** 2021-02-20 18:33 UTC

**Comment by lavarith** [comment] 2022-05-31 13:41
I ran into a very related issue that I wanted to share in case others have the same problem.

Despite having xcode installed, no matter what I did `pip install -U crcmod` didn't result in it compiling for gsutil. It turns out, that I didn't accept the xcode license and that was preventing it compiling. To do that, run `sudo xcodebuild -license` and agree to the TOS. Then, uninstall and reinstall crcmod.
