### ISSUE TITLE
gsutil rsync include option

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/gsutil#636] opened 2019-02-27 20:44 UTC
gsutil support only excludes option, building opposite excludes it is a very painful way of working.
Please provide include patter option example: (XXX|YYY).csv

**Comment by houglum** [comment] 2019-03-07 05:50
Thanks for the report! We've got an open feature request for this in #327, so I'm going to close this as a duplicate of that issue.

**Closed by houglum** 2019-03-07 05:50 UTC
