### ISSUE TITLE
`cp -r` with wildcard path results in incorrect copies

### ISSUE THREAD

**Issue by w4-sjcho** [GoogleCloudPlatform/gsutil#406] opened 2017-01-18 02:47 UTC
If I run the following commands:
```shell
export BUCKET=gs://gsutil-test-$(date +%s)
gsutil mb ${BUCKET}
echo "test file" > testfile
gsutil cp testfile ${BUCKET}/hello_world/hello_universe/testfile
gsutil cp testfile ${BUCKET}/hello_world/hello_universe/foo_bar/testfile
mkdir tmp
gsutil cp -r ${BUCKET}/*/hello_universe tmp
find tmp
```

This is the actual result I get:
```
tmp
tmp/ello_world
tmp/ello_world/hello_universe
tmp/ello_world/hello_universe/foo_bar
tmp/ello_world/hello_universe/foo_bar/testfile
tmp/ello_world/hello_universe/testfile
```

But the result I expect is actually:
```
tmp
tmp/hello_universe
tmp/hello_universe/foo_bar
tmp/hello_universe/foo_bar/testfile
tmp/hello_universe/testfile
```

I can get the expected result using this command:
```shell
gsutil cp -r $(gsutil ls -d ${BUCKET}/*/hello_universe) tmp
```

The version I'm using is:
```shell
$ gsutil --version
gsutil version: 4.22
```

**Comment by thobrla** [comment] 2017-01-18 17:53
Thanks for the report.  This is a duplicate of https://github.com/GoogleCloudPlatform/gsutil/issues/397.  The fix is already committed and it will be included in the next release of gsutil (4.23).

**Closed by thobrla** 2017-01-18 17:53 UTC
