### ISSUE TITLE
The tool that automatically adapts code from py2 to py3 has some limitations

### ISSUE THREAD

**Issue by ADiegoCAlonso** [GoogleCloudPlatform/gsutil#560] opened 2018-09-25 20:11 UTC
No critical, just aesthetics

All the `print ('Hello World!')` statements are converted to `print(('Hello World!'))`

https://github.com/GoogleCloudPlatform/gsutil/compare/py-six#diff-f16a7d04109c5ff8e8e0e9433e5c60c4L349

**Comment by catleeball** [comment] 2019-05-08 21:26
Hi @ADiegoCAlonso ! Thanks for pointing this out! We recently merged Python 2 / 3 compatibility changes into master (PR #735 ) and have smoothed out some of the weirdness caused by previous tools. Please let me know if you see any other spots that could be improved! :slightly_smiling_face:

**Closed by catleeball** 2019-05-08 21:26 UTC

**Comment by ADiegoCAlonso** [comment] 2019-05-11 22:05
@catleeball thank you! 
btw, now we are colleagues ;)
