### ISSUE TITLE
gsutil rsync -r folder with csv.gz files is not working as expected

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/gsutil#635] opened 2019-02-27 20:41 UTC
1. Folder with .csv.gz files
2. gsutil rsync -r the folder with .csv.gz files
3. gsutil is trying to be too smart and gunzip the files (not expected behaviour)
4. next gsutil rsync -r copy again all the files

Expected behaviour gsutil rsync to don't have the extension of the files

**Comment by houglum** [comment] 2019-03-07 05:47
I can't reproduce this with gsutil v4.36 on Linux.

```shell
$ BUCKET=my-bucket-name-here

$ mkdir /tmp/rsync-me-with-csv-gz
$ cd /tmp/rsync-me-with-csv-gz
# Create both regular and gzipped files, and in nested directories
# so that we can test the `-r` in `rsync -r`.
$ echo "regular-text" > text.txt
$ mkdir contains-gzipped-files
$ cd contains-gzipped-files
$ echo "1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9" > nums.csv
$ cp nums.csv nums.csv.bak
$ gzip nums.csv
# And throw a regular file in here too, because why not...
$ echo "pewpew" > file.txt

# So, now we have this directory that we'll sync:
$ tree /tmp/rsync-me-with-csv-gz/
/tmp/rsync-me-with-csv-gz/
├── contains-gzipped-files
│   ├── file.txt
│   ├── nums.csv.bak
│   └── nums.csv.gz
└── text.txt

1 directory, 4 files

# Show that the .csv.gz version is, in fact, compressed and has fewer bytes:
$ ls -alh /tmp/rsync-me-with-csv-gz/contains-gzipped-files/nums.cs*
-rw-r--r-- 1 [user] [group] 54 Mar  6 21:28 /tmp/rsync-me-with-csv-gz/contains-gzipped-files/nums.csv.bak
-rw-r--r-- 1 [user] [group] 51 Mar  6 21:26 /tmp/rsync-me-with-csv-gz/contains-gzipped-files/nums.csv.gzfiles/nums.csv.gz

$ gsutil rsync -r /tmp/rsync-me-with-csv-gz/ gs://$BUCKET/rsyncdir/
Building synchronization state...
Starting synchronization...
Copying file:///tmp/rsync-me-with-csv-gz/contains-gzipped-files/file.txt [Content-Type=text/plain]...
Copying file:///tmp/rsync-me-with-csv-gz/contains-gzipped-files/nums.csv.bak [Content-Type=application/x-trash]...
Copying file:///tmp/rsync-me-with-csv-gz/contains-gzipped-files/nums.csv.gz [Content-Type=text/csv]...
Copying file:///tmp/rsync-me-with-csv-gz/text.txt [Content-Type=text/plain]...  
\ [4 files][  125.0 B/  125.0 B]                                                
Operation completed over 4 objects/125.0 B.                               

# .csv.gz file still has 51 bytes, and thus has not been unzipped
$ gsutil ls -l gs://$BUCKET/rsyncdir/**
         7  2019-03-07T05:29:27Z  gs://[BUCKET]/rsyncdir/contains-gzipped-files/file.txt
        54  2019-03-07T05:29:27Z  gs://[BUCKET]/rsyncdir/contains-gzipped-files/nums.csv.bak
        51  2019-03-07T05:29:28Z  gs://[BUCKET]/rsyncdir/contains-gzipped-files/nums.csv.gz
        13  2019-03-07T05:29:28Z  gs://[BUCKET]/rsyncdir/text.txt

TOTAL: 4 objects, 125 bytes (125 B)

# Also still gzipped when rsync'ing back:
$ mkdir /tmp/rsync-mirror
$ gsutil rsync -r gs://$BUCKET/rsyncdir/ /tmp/rsync-mirror/
Building synchronization state...
Starting synchronization...
Copying gs://[BUCKET]/rsyncdir/contains-gzipped-files/file.txt...
Copying gs://[BUCKET]/rsyncdir/contains-gzipped-files/nums.csv.bak...               
Copying gs://[BUCKET]/rsyncdir/contains-gzipped-files/nums.csv.gz...                
Copying gs://[BUCKET]/rsyncdir/text.txt...                                          
\ [4 files][  125.0 B/  125.0 B]                                                
Operation completed over 4 objects/125.0 B.                                      

$ ls -alh /tmp/rsync-mirror/**
-rw-r--r-- 1 [user] [group]   13 Mar  6 21:29 /tmp/rsync-mirror/text.txt

/tmp/rsync-mirror/contains-gzipped-files:
total 20K
drwxr-xr-x 2 [user] [group] 4.0K Mar  6 21:43 .
drwxr-xr-x 3 [user] [group] 4.0K Mar  6 21:43 ..
-rw-r--r-- 1 [user] [group]    7 Mar  6 21:25 file.txt
-rw-r--r-- 1 [user] [group]   54 Mar  6 21:28 nums.csv.bak
-rw-r--r-- 1 [user] [group]   51 Mar  6 21:26 nums.csv.gz
```

Thus, closing this for now.  If you're able to reproduce this, please comment and provide a detailed reproduction script like the one above, along with the OS version and version of gsutil you're using. Thanks!

**Closed by houglum** 2019-03-07 05:47 UTC

**Comment by VelizarVESSELINOV** [comment] 2019-03-13 16:35
@houglum Please try to add blob meta property `Content-Encoding` setup as `gzip` in order to reproduce the exact problem.

**Comment by schnekke** [comment] 2019-03-13 16:42
@houglum  i presume this is expected behaviour, called decompressive transcoding, the point is adding -h 'Accept-Encoding: gzip' to gsutil command does not seem to help as mentioned in  https://cloud.google.com/storage/docs/transcoding

**Comment by houglum** [comment] 2019-03-13 22:46
Ah, I see.  That wasn't mentioned in the original repro steps, which explains why I couldn't reproduce this.  And yes, `gsutil help options` doesn't include the `Accept-Encoding` header.  In fact, you should get an error if you try to specify it:

```
gsutil -h 'Accept-Encoding: gzip' cp gs://$BUCKET/rsyncdir/contains-gzipped-files/nums.csv.gz /tmp/csvthing
ArgumentException: Invalid header specified: accept-encoding: gzip
```

That being said, I'm guessing this isn't so much of a bug as it is a feature request? That is, to be able to to tell `gsutil rsync` that it should not decompress objects that you've manually changed metadata for by setting `Content-Encoding: gzip`?

Note that there is one workaround, if you want gsutil to copy your gzipped files back to your disk untransformed -- you can set `Cache-Control: no-transform` on the object.  `gsutil cp -Z` does this in addition to setting `Content-Encoding: gzip`.

**Comment by VelizarVESSELINOV** [comment] 2019-03-14 00:12
@houglum the challenge we are facing is to make work `gsutil rsync` without the possibility to change the bucket metadata as we have only read-only access to the source bucket. Yes, we are aware that we can copy or do `fake rsync` (restarting copy from scratch each time we rsync). The question is `gsutil` able to do proper `rsync` without changing the source bucket metadata but only adding some extra arguments to avoid gunzip the file on the destination folder.

**Comment by schnekke** [comment] 2019-03-14 15:47
@houglum we permitted to change none of objects' metadata, so `no-transform` is of little help, as to `cp -Z` it does not help as well:
![image](https://user-images.githubusercontent.com/39571350/54370772-39082180-4646-11e9-99f6-ce42431cf61b.png)
