### ISSUE TITLE
gsutil signurl — Failure: __init__() takes exactly 4 arguments (2 given)

### ISSUE THREAD

**Issue by tskir** [GoogleCloudPlatform/gsutil#394] opened 2016-12-06 21:07 UTC
Hi! When I run this command:

```
gsutil signurl -d 10m -p notasecret service_account_key.p12 gs://[REDACTED]/rawdata/**
```

It crashes with the following error message:

```
Failure: __init__() takes exactly 4 arguments (2 given).
```

The glob ending in `**` expands to 10 files in total. Before crashing, the command outputs correctly formed and working links for _some_ of those files, but the number of them is not consistent. Just before posting this, I ran the command three times (one after another), and it crashed after printing 6; 3; and 4 links.

I'm having no issues with internet connection or permissions for that directory in storage, and other gsutil commands work just fine for me. I'm using `gsutil version: 4.22`, the latest available at the moment.

**Comment by thobrla** [comment] 2016-12-07 21:25
This sounds like a bug in `gsutil signurl` at first glance.

Could you run `gsutil -D signurl -d 10m -p notasecret service_account_key.p12 gs://[REDACTED]/rawdata/**` and provide a stack trace for that failure?

**Comment by tskir** [comment] 2016-12-07 21:36
Sure:

```
DEBUG: Exception stack trace:
    Traceback (most recent call last):
      File "/home/[REDACTED]/software/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 577, in _RunNamedCommandAndHandleExceptions
        collect_analytics=True)
      File "/home/[REDACTED]/software/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 299, in RunNamedCommand
        return_code = command_inst.RunCommand()
      File "/home/[REDACTED]/software/google-cloud-sdk/platform/gsutil/gslib/commands/signurl.py", line 415, in RunCommand
        key, client_email, gcs_path, self.logger)
      File "/home/[REDACTED]/software/google-cloud-sdk/platform/gsutil/gslib/commands/signurl.py", line 344, in _ProbeObjectAccessWithClient
        raise HttpError(response)
    TypeError: __init__() takes exactly 4 arguments (2 given)
```

**Comment by tskir** [comment] 2016-12-07 21:43
Also, this happens right before the trace:

`send: 'HEAD /[REDACTED:BUCKET+PATH]/rawdata/[REDACTED:FILENAME]?GoogleAccessId=[REDACTED]&Expires=1481146107&Signature=[REDACTED] HTTP/1.1\r\nHost: storage.googleapis.com\r\ncontent-length: 0\r\naccept-encoding: gzip, deflate\r\nuser-agent: Python-httplib2/0.7.7 (gzip)\r\n\r\n'`

`reply: 'HTTP/1.1 400 Bad Request\r\n'`

**Comment by thobrla** [comment] 2016-12-07 23:00
It looks like there are two issues here.  First, there is a bug in `gsutil` generating the HTTPError class from the failed HEAD call.  That should be straightforward to fix.

Second, there is the question of why you are getting 400s in response to the HEAD call in the first place.  My initial suspicion is that something is not being encoded properly contingent upon which characters are present in the signature.  That would be a little surprising since at a glance the HEAD request appears to be properly URL-encoded.  Can you reproduce this with a test bucket/object that you don't mind exposing the full signature for?

**Comment by tskir** [comment] 2016-12-08 00:22
I created a test bucket `gs://issue-394-bucket/`, which contains one directory `rawdata/`, which in turn contains 10 files from `0.txt` to `9.txt`, and could indeed reproduce the issue. The exact command was:

```
gsutil -D signurl -d 30d -p notasecret service_account_key.p12 gs://issue-394-bucket/rawdata/**
```

The stack trace was exactly as above. Here are the lines in the log where everything went as planned — 200 OK for `0.txt`:

```
gs://issue-394-bucket/rawdata/0.txt	GET	2017-01-07 03:09:28	https://storage.googleapis.com/issue-394-bucket/rawdata/0.txt?GoogleAccessId=115360193262961020729&Expires=1483747768&Signature=6gdOCUJ1WDV9N7Xm1MPNAezXpWjW8flFwNrzqAxn%2Fq6ldbdHCfhqoOq7LCSWtaulnD%2BR2YH45mqHzRFozhTgkU0hvY449xaJYEyG%2Ff4ODqsO06Zo%2FMNhkKQxp6OAIDwKrnkWHNzYXcthOwzRmbJ4Jv11UEbKNMOZZD%2FVs4ibL88Io7X09I3qpWsAz6g2J%2F6X2%2BgwUkf9Fmph9pnPL2cPQa2YVBjclJDoJaaiRJu5XEt4wcv%2F7KFilefpoqaoqpyfKOpwZ%2FJFpClHMODIBJsGP%2BWI1Sr0zoZxJ9J8Z6Fq%2BfbccJlcv6FkvZcrAXNIZ%2BemrIJn5TwZeaAktkCW1Eur%2Bw%3D%3D
connect: (storage.googleapis.com, 443)
send: 'HEAD /issue-394-bucket/rawdata/0.txt?GoogleAccessId=115360193262961020729&Expires=1481155783&Signature=MJ9KSqjNSmgAoDAcCtEGp7%2FhCbIQQgw3nXLRTSrEuKmIIzR%2BafNdtNIu1INJFTObgEZjsXOMYA2H%2BznLsDal%2FerQOFaFbrXv7n%2Fwb3vk4oDkYGXdclx4RWJqB5RZnOMkfpB9tfe4TPl6S%2F9ILTMgf7X7eTl4UAs0NA4ikSVQRhXTdprSwgBL1LIxeDnlSwrSFYD5%2BK9qKfL4NAZ5AfCOJYIQ3O7Y0fUC9rOqhYMn%2FtmVQtKlImcWlopB6rDdO7Fr0xJ08DPkjyka3%2Bdtp27jMOvbz1CEoL0FPDqK9%2BEzWZrcNv44qTde2aAO3eTtiDVYKEk9%2F6gPkCmaSSDQjwpPgA%3D%3D HTTP/1.1\r\nHost: storage.googleapis.com\r\ncontent-length: 0\r\naccept-encoding: gzip, deflate\r\nuser-agent: Python-httplib2/0.7.7 (gzip)\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
```

And here is the error — 400 Bad Request for `1.txt`:

```
gs://issue-394-bucket/rawdata/1.txt	GET	2017-01-07 03:09:28	https://storage.googleapis.com/issue-394-bucket/rawdata/1.txt?GoogleAccessId=115360193262961020729&Expires=1483747768&Signature=wCfmomZ2uEOwFoJ5E1XvfyZyfEq3ioh3oQHYu7cQ8DuHmyl%2BgKupxQV6lgqqPc8A0jQiUkM0ZmOx%2BiZLvqYHGYmWEDUNb8AWofp%2BTkqYSXmGNtgWR0nHML6ZdR%2FnXSQLwe2LcoWYEBwj8hFGRG9q0Z8tqNtUKNHlW%2Biu%2Bx%2BOtfEHpMWMzd02R1n8tHSoFVjhuj%2FA%2BcgVf%2FxhWgbU5nzWbyYy%2FHBr499LceffitvOuR3GwtkFQdBMhXTHWxKdGuo8N6Nver7AfiA%2BI4%2BrVF0K%2B3gCYTzq6o1%2FEpVlyM8LJtT7QcfzmCUsamxk2QB%2FpzM%2BxkL%2BC6u7%2F0ZMIKqPyvgW0w%3D%3D
connect: (storage.googleapis.com, 443)
send: 'HEAD /issue-394-bucket/rawdata/1.txt?GoogleAccessId=115360193262961020729&Expires=1481155784&Signature=6aBF4bARdUPVi1B8Y1LZ%2FR8MOJtHarF1NQzWVRjs2LlL9Us7ngrnVgH%2BDSSivhcqa%2FwjoX7pf%2BPNeSKpMEWVgSur99nLOJOLIhUk6Na2GFUAj78n50NxmcU99cF5HAm2AdE7HONdkT5HlE862GU7AV2Kc7nQfRJrx2GdjgMwxqZJKcbbKgIIAFLTxy0EKfbYXCjAq%2BCi8xhNQGV4YtxzCaDeQaTaQN7bJuXRSoIXimR32bmTf2Pqw24Ai2OY%2FhqLiHwxhzYTG%2FGN1yierHyWGCFFTvlqNNDFGVqDV5p5uY4DVePYU%2Bj%2BVXXl%2FyFsvcrscfkV%2BC%2Fkaak7u2whQADvZQ%3D%3D HTTP/1.1\r\nHost: storage.googleapis.com\r\ncontent-length: 0\r\naccept-encoding: gzip, deflate\r\nuser-agent: Python-httplib2/0.7.7 (gzip)\r\n\r\n'
reply: 'HTTP/1.1 400 Bad Request\r\n'
```

Both links that were printed to the user work **correctly** when opened. However, in the first case HEAD request was OK and in the second case it returned 400.

**Comment by tskir** [comment] 2016-12-08 00:31
Also I noticed a couple of strange things with timestamps.

First, in both cases expiration timestamp of the second link (to which HEAD request is sent) does not match timestamp of the first link (which is printed to the user). But maybe that's actually how it's supposed to be; I don't know how `signurl` internals work.

Second, much more interestingly, timestamps of second links are in the _very_ near future, possibly even _in the past._ The command in my previous comment started running at precisely 14811557**66**, and terminated at 14811557**90**. Expiration timestamps of second links are 14811557**83** and 14811557**84**. Might it be possible that `400 Bad Request` happens because the link has already expired?

Before running the command in my previous message, I synchronized system clock with `sudo ntpdate -s time.nist.gov`, so I'm certain that my time settings are reasonably correct.

**Comment by tskir** [comment] 2016-12-08 01:26
In fact, after editing [line 336 of signurl.py](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/commands/signurl.py#L336) to add **60** seconds instead of 10, I can no longer reproduce this issue. Twelve full runs of the command above raised no errors and produced working links for all ten files. So it does appear to be a timestamp problem: requests aren't always able to complete in 10 seconds.

**Comment by thobrla** [comment] 2016-12-08 22:39
Thanks for the detailed investigation.  The __init__ issue should be fixed for gsutil 4.23.

I think you're correct about short expiration being the reason for the 400.  The expiration is chosen from the system time at the start of the command, not a series of rolling start times per-object.  However, the validity of the URLs is checked serially.  So by the time the HEAD call is issued for the last few objects, the URLs are past their short expiration time.

Whether the URL is still valid when we probe it boils down to {client latency to GCS * number of objects < expiration time}.

Some potential options:
- Change to a rolling start time.  This makes it hard to ensure a set of objects expire by a certain fixed time.
- Add an option to disable access probing.  I worry such an option will confuse users who use it unwittingly, for example by copying and pasting from a power user's command.
- Include an error message hint when we get a 400 (can compare the current system time with the initial expiration).

I like improving the error message the best.  Thoughts?

**Comment by tskir** [comment] 2017-01-02 12:40
Sorry for disappearing for a while... 

> Some potential options:
> * Change to a rolling start time.

Actually, I think rolling expiration time is already being used, just that the time delta is too short. Assuming I'm reading the code right, it does the following for each link:

1. [Generate](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/commands/signurl.py#L406) `final_url` and print it to the output. All final_urls have the same expiration time set by the user, computed during parsing of command line parameters. This URL is *never* checked for availability, no HEAD requests are ever sent.
2. [Call](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/commands/signurl.py#L417) `self._ProbeObjectAccessWithClient`, which [generates another link](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/commands/signurl.py#L335) `signed_url`. Its expiration time is derived as **current** system time plus a fixed amount of **10 seconds**, so it *is* rolling.
3. This second URL, `signed_url`, is then checked for availability. If `latency to cloud` − `system time discrepancy` > 10 seconds, then the request fails, because the link has already expired. For instance, if my latency to cloud is 7 seconds (router at a local traffic exchange point had a hiccup...) and my system clock is 5 seconds behind (discrepancy = −5), then URL check will fail. If my clock is 15 seconds behind, then URL check will *always* fail.

So, basically the problem is that those temporary URLs that are actually checked for validity live only for 10 seconds, and that isn't enough for many situations. I changed that to 60 seconds in my local installation, and have never had a problem since.

Based on that, I have two proposals of my own:

* Increase time delta from 10 seconds to some other value. 60 works for me, and request latency is very unlikely to reach such high levels, but it will still fail for users if their clock is more than a minute behind. Maybe gsutil should advise user to synchronize their clock if an error still occurs.

* Alternatively, how about just checking the `final_url` itself for availability without generating any temporary URLs? It even seems more consistent, because in this case we're checking the same URL that will be printed to the user, not some other temporary one.

**Comment by thobrla** [comment] 2017-01-10 02:16
You are correct in your analysis - I didn't notice when I read through the code the first time that we were using a fixed value.  Thanks for pointing that out.

Checking final_url isn't feasible because we only want to probe with HEAD (we shouldn't, for example, PUT data for a PUT signed URL, or start a resumable upload).  So I like your first suggestion of increasing the timeout to 60, which will increase resilience.  It will still be problematic if the user's system clock substantially diverges, but this should cover most cases.

**Closed** 2017-01-10 17:24 UTC

**Comment by kilianc** [comment] 2017-02-05 13:26
I am experiencing this inside an ubuntu container with `142.0.0`. Is there any workaround I can use to make this work?

**Comment by houglum** [comment] 2017-02-06 20:42
The commit thobrla made should address this; we're planning on testing and hopefully releasing v4.23 of gsutil in a couple of weeks. That version should contain a fix for the issue you're seeing.
