### ISSUE TITLE
Gzipping and Cache-Control: no-transform

### ISSUE THREAD

**Issue by ygt-rclarke** [GoogleCloudPlatform/gsutil#363] opened 2016-06-14 09:39 UTC
We push gzipped versions of our website's static assets through gsutil up to GCS as part of our deployment, and we've noticed that some browsers (notably Microsoft Edge 12) have been broken since we upgraded to gsutil 4.18.

The problem seems to be [this block](https://github.com/GoogleCloudPlatform/gsutil/commit/439573e7266d8e309f9a1d0364fa91379e3a7b21#diff-7e73ba8eced7ee2a2ff38943a9075536R1588) which adds the `Cache-Control: no-transform` header, but it's not configurable in any way.   Edge 12 doesn't send the `Accept-Encoding: gzip` header by default, and it won't decompress a gzipped response, so we rely on the auto-decompression that GCS does otherwise the assets are mangled.

I realise the change was made deliberately to make the integrity checking in GCS work, but is there a workaround for clients that don't `Accept-Encoding: gzip`?  Or another way to efficiently host assets through GCS without gzipping them first?  If not, is it possible that the `no-transform` header could be made optional?

Thanks,
Rob

**Comment by thobrla** [comment] 2016-06-14 16:49
I think your scenario is valid.  There are two ways that I can think of to approach a fix:
1. If cache-control is specified directly (even as blank) on the command line, we honor it and don't amend it.
2. We add a flag value that disables this behavior.

The second solution means adding a flag for a very specific scenario, and while I don't like that, I think it's better than the first because that one would cause us to accidentally lose integrity checking capability in some cases.

**Comment by thobrla** [comment] 2016-06-14 21:06
We've agreed that adding a flag to disable this behavior is likely the correct path forward.  There's a fair chance it won't be ready for the next release, though.  In the meantime, you should be able to manually override the cache-control on your objects via a command like:

`gsutil -m setmeta -h 'Cache-Control:' gs://yourbucket/yourobject`

You'll need to adjust the header to match your preference, but you can remove no-transform via this mechanism.

If you do this immediately after upload, this will mean there is only a brief period in which your objects are not visible to browsers not supporting Accept-Encoding:gzip.

As an aside, gzip encoding is fairly ubiquitous, so it may be worth following up with the Edge 12 team to see if they are willing to fix this issue.

**Comment by ygt-rclarke** [comment] 2016-06-15 10:18
Thanks for the quick response, and the workaround. I think I'd appreciate the flag for backwards compatibility purposes, but I was surprised that other people weren't reporting the same behaviour.

In our case I've realised it's an artifact of our test suite, as the headers included by Edge are due to a registry key somewhere, and I don't know of any other clients we have to support that don't gunzip automatically. The current release of Edge (13) works properly. So I leave it up to you whether to implement the flag or not, if it's there we would use it, but the workaround works equally well.

**Comment by thobrla** [comment] 2016-06-15 17:50
Given that all modern browsers support accept-encoding:gzip, I don't think adding the flag is a good idea, as it makes it easier for users to get into a situation where data integrity checking doesn't work.  With that in mind I'm going to close this request.  The workaround I suggested in https://github.com/GoogleCloudPlatform/gsutil/issues/363#issuecomment-226016228 is still viable if it comes up again.

**Closed by thobrla** 2016-06-15 17:50 UTC

**Comment by csilvers** [comment] 2016-09-07 00:27
This bug also seems to affect `gsutil cat`, and I'm sure it affects other commandline fetching. (It affects curl by default, and also python's urllib2.)  I would encourage you to revisit the decision not to decompress automatically for clients that don't pass `Accept-encoding`.

The comments in the code seem to indicate the problem is only with uncompressible content.  Would it be possible to only set the no-transform header for content-types that are uncompressible?  I am trying to fetch a .js file with `gsutil cat` but also have it be accessible to web clients, so the issue with uncompressible content doesn't apply to me.

(Or at the least, make `gsutil cat` do the right thing with gzipped encodings!)

**Comment by csilvers** [comment] 2016-09-07 00:29
Also, a question: do we need to use `setmeta` or would it work to do something like `gsutil cp -r -z js -h 'Cache-control:'`.

And if we wanted this to be cacheable, would it be appropriate to say `-h 'Cache-control: public'` instead? or is that controlled somewhere else?

**Comment by thobrla** [comment] 2016-09-23 15:53
Sorry for the slow reply.  I think the ultimate problem here is that `cache-control` header that the service responds with is controlled primarily by the object metadata, and only somewhat by the client request.  The client can send a request with or without `accept-encoding:gzip`, but there is no way for the client to request that the `cache-control` for the object be treated a certain way without actually modifying the object's metadata.

As such, it's not really possible to make `gsutil cat` do the right thing for such an object, unless we grant `cat` the permission to actually modify the object's metadata, which seems like the wrong thing to do.

I'll discuss this with the service authors and see if there's anything more we can do there.

**Comment by thobrla** [comment] 2016-09-23 15:55
As for your second question, currently `setmeta` is required.  Above, we considered adding a flag to make it behave differently.

You can set `-h 'Cache-control: public'` and that will be converted by `gsutil` to `Cache-control: public,no-transform'`

**Comment by csilvers** [comment] 2016-09-23 17:12
Yep, that's exactly what we found.  Right now we're doing a big `setmeta gs://bucket/**` after the `cp`, which isn't ideal because of eventual consistency, but we got it to work.
