### ISSUE TITLE
PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()

### ISSUE THREAD

**Issue by 747project** [GoogleCloudPlatform/gsutil#594] opened 2018-12-28 16:17 UTC
Requesting that #390 be re-opened please, as it is still happening. Just happened for me when attempting to transfer ~150K files. Had to terminate the process after ~90K files were transferred, and restart it again to finish the rest.

**Comment by DollarAkshay** [comment] 2018-12-31 07:35
Having the same issue. gsutil was working fine till November last week. All of a sudden a lot of the files stopped getting copied to GCS and I kept seeing this error.

**Comment by blinkseb** [comment] 2019-01-03 09:17
seeing the same issue when running a `gsutil -m cp` with many files. Seems to occur only when the token has expired and need to be refreshed:

```
INFO 1217 19:02:15.830502 client.py] access_token is expired. Now: 2018-12-17 19:02:15.830482, token_expiry: 2018-12-17 19:02:15
INFO 1217 19:02:15.830906 base_api.py] Headers: {'accept': 'application/json',
 'accept-encoding': 'gzip, deflate',
 'content-length': '0',
 'user-agent': 'apitools gsutil/4.28 Python/2.7.9 (linux2) google-cloud-sdk/191.0.0 analytics/disabled'}
INFO 1217 19:02:15.831024 base_api.py] Body: (none)
INFO 1217 19:02:15.831145 client.py] Attempting refresh to obtain initial access_token
PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()


Encountered exception while copying:
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/command.py", line 2109, in PerformTask
    results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 753, in _CopyFuncWrapper
    preserve_posix=cls.preserve_posix_attrs)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 947, in CopyFunc
    preserve_posix=preserve_posix))
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 3236, in PerformCopy
    dst_url.bucket_name, dst_url.object_name, provider=dst_url.scheme)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 253, in GetObjectMetadata
    bucket_name, object_name, generation=generation, fields=fields)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 783, in GetObjectMetadata
    global_params=global_params)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/third_party/storage_apitools/storage_v1_client.py", line 1086, in Get
    download=download)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/base_api.py", line 720, in _RunMethod
    http, http_request, **opts)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 351, in MakeRequest
    max_retry_wait, total_wait_sec))
  File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/util.py", line 1723, in WarnAfterManyRetriesHandler
    http_wrapper.HandleExceptionsAndRebuildHttpConnections(retry_args)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 341, in MakeRequest
    check_response_func=check_response_func)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 391, in _MakeRequestNoRetry
    redirections=redirections, connection_type=connection_type)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/client.py", line 616, in new_request
    self._refresh(request_orig)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/client.py", line 885, in _refresh
    self._do_refresh_request(http_request)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/client.py", line 900, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/client.py", line 1611, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/service_account.py", line 396, in _generate_assertion
    key_id=self._private_key_id)
    signature = signer.sign(signing_input)
  File "/usr/lib/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/_pycrypto_crypt.py", line 101, in sign
    return PKCS1_v1_5.new(self._key).sign(SHA256.new(message))
  File "/usr/lib/python2.7/dist-packages/Crypto/Signature/PKCS1_v1_5.py", line 112, in sign
    m = self._key.decrypt(em)
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 174, in decrypt
    return pubkey.pubkey.decrypt(self, ciphertext)
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/pubkey.py", line 93, in decrypt
    plaintext=self._decrypt(ciphertext)
  File "/usr/lib/python2.7/dist-packages/Crypto/PublicKey/RSA.py", line 235, in _decrypt
    r = getRandomRange(1, self.key.n-1, randfunc=self._randfunc)
  File "/usr/lib/python2.7/dist-packages/Crypto/Util/number.py", line 123, in getRandomRange
    value = getRandomInteger(bits, randfunc)
  File "/usr/lib/python2.7/dist-packages/Crypto/Util/number.py", line 104, in getRandomInteger
    S = randfunc(N>>3)
  File "/usr/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/usr/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/usr/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 137, in read
    self._check_pid()
  File "/usr/lib/python2.7/dist-packages/Crypto/Random/_UserFriendlyRNG.py", line 153, in _check_pid
    raise AssertionError("PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()")
AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()
```

**Comment by houglum** [comment] 2019-01-11 00:40
Reopened, thanks for the report.  I'll close this one as a duplicate of #390.

**Closed by houglum** 2019-01-11 00:40 UTC
